# Generated by Django 2.2.1 on 2019-05-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=8)),
                ('season', models.CharField(choices=[('0', 'Any'), ('1', 'Fall'), ('2', 'Spring')], max_length=1)),
                ('credit_hours', models.IntegerField(default=0)),
                ('laboratory',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_course',
                                   to='curriculum_algorithm.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_requisites', models.ManyToManyField(related_name='_curriculumcourse_co_requisites_+',
                                                         to='curriculum_algorithm.CurriculumCourse')),
                ('course',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_algorithm.Course')),
                ('curriculum',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_algorithm.Curriculum')),
                ('pre_requisites', models.ManyToManyField(related_name='_curriculumcourse_pre_requisites_+',
                                                          to='curriculum_algorithm.CurriculumCourse')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_credits', models.IntegerField(default=0)),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 to='curriculum_algorithm.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_full', models.BooleanField(default=False)),
                ('past', models.BooleanField(default=False)),
                ('credit_hours', models.IntegerField(default=0)),
                ('max_credits', models.IntegerField()),
                ('position', models.IntegerField(default=0)),
                ('curriculum_courses', models.ManyToManyField(to='curriculum_algorithm.CurriculumCourse')),
                ('student_plan',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_algorithm.StudentPlan')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='courses',
            field=models.ManyToManyField(through='curriculum_algorithm.CurriculumCourse',
                                         to='curriculum_algorithm.Course'),
        ),
    ]
