# Generated by Django 2.2.1 on 2019-05-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('curriculum_algorithm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='credit_hours',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='co_requisites',
            field=models.ManyToManyField(related_name='enmendated_bops', to='curriculum_algorithm.CurriculumCourse'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='pre_requisites',
            field=models.ManyToManyField(related_name='bops', to='curriculum_algorithm.CurriculumCourse'),
        ),
    ]
