# Generated by Django 2.2.1 on 2019-05-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('curriculum_algorithm', '0002_auto_20190527_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcourse',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='credit_hours',
            field=models.IntegerField(default=0),
        ),
    ]
