# Generated by Django 2.2.1 on 2019-07-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('curriculum_algorithm', '0003_auto_20190527_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='max_credits',
            field=models.PositiveIntegerField(),
        ),
    ]
