# Generated by Django 2.2.1 on 2019-11-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('curriculum_algorithm', '0006_planwarning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planwarning',
            name='target',
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='plan_warnings',
            field=models.ManyToManyField(
                to='curriculum_algorithm.PlanWarning'),
        ),
        migrations.AddField(
            model_name='semester',
            name='plan_warnings',
            field=models.ManyToManyField(
                to='curriculum_algorithm.PlanWarning'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='co_requisites',
            field=models.ManyToManyField(related_name='co_unlocked',
                                         to='curriculum_algorithm.CurriculumCourse'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='pre_requisites',
            field=models.ManyToManyField(related_name='unlocked',
                                         to='curriculum_algorithm.CurriculumCourse'),
        ),
    ]
